#### 几个工具或者说是库
- unittest
- mock
- coverage
- testtools
- tox

#### 目录
* [windows上工具的安装](####2)

<h2 id="1">windows上工具的安装</h2>
#### windows上工具的安装
mock依赖于pbr，funcsigs

#### unittest
- 执行方法一: 指定文件执行 ```python -m unittest 文件名```
- 执行方法二: 搜索目录下所有文件执行 ```python -m unittest discover```
- 要求：1. 每个测试函数名称都必须以test开头。 2. discover只搜索test*.py的文件
- 高级用法：两个装饰器
    - skipif: 如果表达式为真，跳过 ```@unittest.skipif(True, 'test')```
    - skipUnless：如果表达式为假，跳过

```python -m unittest discover -s com/fisher/unittest```
##### 实例
测试的函数
```python
def fibonacci(maxloop):
    numbers = []
    loop_i = 0
    while True:
        loop_i = loop_i + 1
        if len(numbers) < 2:
            numbers.append(1)
        else:
            numbers.append(sum(numbers))
            #memmory
            numbers.pop(0)
        if (loop_i > maxloop):
            raise StopIteration
        yield numbers[-1]
```
测试代码
```python
# -*- coding: utf-8 -*
import unittest
from com.fisher.util.common_util import *

class TestUtil(unittest.TestCase):
    def test_fibonacci(self):
        gen = fibonacci(6)
        self.assertEquals(next(gen), 1)
        self.assertEquals(next(gen), 1)
        self.assertEquals(next(gen), 2)
        self.assertEquals(next(gen), 3)
        self.assertEquals(next(gen), 5)
        self.assertEquals(next(gen), 8)

```
输出结果
```
Ran 1 test in 0.001s

OK
```

#### mock 模拟
**解决的问题：** 单元测试中通常有一部分函数是依赖于外部无法测试的，比如说需要和某个服务器交互获取信息，如果想要对使用这种函数的函数做单元测试，就必须要解决这个无法调用的函数的问题，一种方式是重构代码，但是这种重构会破坏代码结构。另一种就是模拟。  
**模拟：** 模拟是在测试中声明特定函数调用给出一个特定输出的过程，而函数调用本身会被禁止。此外你可以以特定方式来断言你所期望的模拟调用。  
mock包在python3.3后是默认包含的。mock模块本质上是一个打补丁的库。它临时将给定命名空间的一个变量替换为一个名称为MagicMock的特殊对象，然后在模拟范围结束后将变量还原为之前的值。

##### mock的几个变量和方法
- ```mock.MagicMock().assert_called_once_with() ``` 被调用且只被调用一次
- ```mock.MagicMock().assert_has_calls()```  判断某些方法是否被调用了
- ```mock.MagicMock().call_count```  调用次数
- ```mock.MagicMock().called```  是否被调用了

##### 实例说明
测试的函数
```
from datetime import date

class TestMockClass():
    def get_person_from_db(self, persion_id):
        raise RuntimeError('The function get_person_from_db '
                       'was called')
    def calculate_age_at_wedding(self, persion_id):
        person = self.get_person_from_db(persion_id)
        anniversary = person['anniversary']
        birthday = person['birthday']

        age = anniversary.year - birthday.year
        if birthday.replace(year=anniversary.year) > anniversary:
            age -= 1
        return age
```
测试代码
```
# -*- coding: utf-8 -*
import unittest
from datetime import date
from com.fisher.highlevel.unit_test import TestMockClass
# python2.7和python3.3兼容
try:
    from unittest import mock
except ImportError:
    import mock

class TestByMock(unittest.TestCase):
    # 装饰器，第一个参数：要替换的函数所在的模块，第二个参数：要替换的函数
    @mock.patch.object(TestMockClass, 'get_person_from_db')
    def test_calculate_age_at_wedding(self, mock_update): # mock_update 装饰器返回的MagicMock的特殊对象
        mock_update.return_value = {'anniversary': date(2012, 4, 21),
                          'birthday': date(1986, 6, 15)}
        testclass = TestMockClass()
        age = testclass.calculate_age_at_wedding(42)
        self.assertEquals(age, 25)

    @mock.patch.object(TestMockClass, 'get_person_from_db')
    def test_calculate_age_at_wedding_error(self, mock_update):
        mock_update.return_value = {'anniversary': date(2012, 4, 21),
                          'birthday': date(1986, 6, 15)}
        testclass = TestMockClass()
        age = testclass.calculate_age_at_wedding(42)
        self.assertEquals(age, 26)

```
测试结果
```
Failure
Traceback (most recent call last):
  File "D:\Program Files\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "D:\Program Files\Python27\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "D:\MyZone\work\code\python\project\python_scrapy\com\fisher\unittest\test_by_mock.py", line 25, in test_calculate_age_at_wedding_error
    self.assertEquals(age, 26)
  File "D:\Program Files\Python27\lib\unittest\case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\Program Files\Python27\lib\unittest\case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 25 != 26

      

Ran 2 tests in 0.005s

FAILED (failures=1)
```

#### coverage
https://pypi.python.org/pypi/coverage 下 coverage.tar.gz 

```
python_scrapy# coverage run -m unittest discover -s com/fisher/unittest
.E.
======================================================================
ERROR: test_calculate_age_at_wedding_error (test_by_mock.TestByMock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/opt/shiguangsheng/python_test/python_scrapy/com/fisher/unittest/test_by_mock.py", line 25, in test_calculate_age_at_wedding_error
    mock.MagicMock().assert_has_calls()
TypeError: assert_has_calls() takes at least 2 arguments (1 given)

----------------------------------------------------------------------
Ran 3 tests in 0.003s

FAILED (errors=1)

python_scrapy# coverage report
Name                                                               Stmts   Miss  Cover
--------------------------------------------------------------------------------------
com/__init__.py                                                        0      0   100%
com/fisher/__init__.py                                                 0      0   100%
com/fisher/highlevel/__init__.py                                       0      0   100%
com/fisher/highlevel/unit_test.py                                     12      1    92%
com/fisher/unittest/test_by_mock.py                                   21      5    76%
com/fisher/unittest/test_utilfunction.py                              11      0   100%
com/fisher/util/__init__.py                                            0      0   100%
com/fisher/util/common_util.py                                        17      3    82%
/usr/local/lib/python2.7/dist-packages/appdirs.py                    250    219    12%
/usr/local/lib/python2.7/dist-packages/funcsigs/__init__.py          432    357    17%
/usr/local/lib/python2.7/dist-packages/funcsigs/version.py             1      0   100%
/usr/local/lib/python2.7/dist-packages/mock/__init__.py                4      0   100%
/usr/local/lib/python2.7/dist-packages/mock/mock.py                 1373    918    33%
/usr/local/lib/python2.7/dist-packages/packaging/__about__.py         10      0   100%
/usr/local/lib/python2.7/dist-packages/packaging/__init__.py           3      0   100%
/usr/local/lib/python2.7/dist-packages/packaging/_compat.py           12      1    92%
/usr/local/lib/python2.7/dist-packages/packaging/_structures.py       41     17    59%
/usr/local/lib/python2.7/dist-packages/packaging/markers.py          130     73    44%
/usr/local/lib/python2.7/dist-packages/packaging/requirements.py      72     17    76%
/usr/local/lib/python2.7/dist-packages/packaging/specifiers.py       284    190    33%
/usr/local/lib/python2.7/dist-packages/packaging/version.py          150     38    75%
/usr/local/lib/python2.7/dist-packages/pbr/__init__.py                 0      0   100%
/usr/local/lib/python2.7/dist-packages/pbr/version.py                218    116    47%
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py    1508    861    43%
/usr/local/lib/python2.7/dist-packages/pyparsing.py                 2527   1359    46%
/usr/local/lib/python2.7/dist-packages/six.py                        444    415     7%
--------------------------------------------------------------------------------------
TOTAL                                                               7520   4590    39%
python_scrapy# coverage html -d covhtml
```
**HTML格式覆盖率说明**
![image](D:\MyZone\youdaoyun\image\python\python_coverage_all.png)
![image](D:\MyZone\youdaoyun\image\python\python_coverage_detail.png)
